In [1]:
import joblib
import pandas as pd

from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, precision_score, recall_score, confusion_matrix

In [2]:
df_churn = pd.read_excel('C:/code/github/churn-project/Telco Churn Solutions/Telco_customer_churn_adapted_v2.xlsx')
churn_model = joblib.load('C:/code/github/churn-project/Telco Churn Solutions/churn_model.joblib')

In [3]:
# preprocessing
df_churn['Internet'] = df_churn['Video Product'].apply(lambda x: 0 if x == 'No internet access' else 1)

In [4]:
# model prediction
X = df_churn[['Tenure Months','Monthly Purchase (Thou. IDR)', 'Device Class', 'Call Center', 'Use MyApp', 'Payment Method', 'Internet',
        'Games Product', 'Music Product', 'Education Product', 'Video Product']]
y = df_churn['Churn Label'].apply(lambda x: 1 if x == 'Yes' else 0)

In [5]:
predictions = churn_model.predict(X)
print(accuracy_score(y, predictions))

0.8067584836007383

In [6]:
churn_model.predict_proba(X.head(1))[:, 1]

array([0.23575619], dtype=float32)

In [20]:
X.head(1)

,Tenure Months,Monthly Purchase (Thou. IDR),Device Class,Call Center,Use MyApp,Payment Method,Internet,Games Product,Music Product,Education Product,Video Product
0,2,70.005,Mid End,No,No,Digital Wallet,1,Yes,Yes,No,No

In [11]:
new_data = pd.DataFrame([{
    'Tenure Months': '2',
    'Monthly Purchase (Thou. IDR)': '2000',
    'Device Class': 'Low End',
    'Call Center': 1, 
    'Use MyApp': 1,
    'Payment Method': 'Pulsa', 
    'Internet': 1,
    'Games Product': 0,
    'Music Product': 1,
    'Education Product': 1,
    'Video Product': 0
}])

In [12]:
new_data

,Tenure Months,Monthly Purchase (Thou. IDR),Device Class,Call Center,Use MyApp,Payment Method,Internet,Games Product,Music Product,Education Product,Video Product
0,2,2000,Low End,1,1,Pulsa,1,0,1,1,0

In [13]:
churn_model.predict_proba(new_data)[:, 1]

array([0.5445823], dtype=float32)